# The overall log-likelihood of the data given the model can be computed 
# by summing over the final column of the matrix generated by the forward algorithm

likelihood_hmm(gold_hmm_5$hmm, unseen_new_obvs)

likelihood_hmm(gold_hmm_5$hmm, clickstreams_test)





